# Generated by Django 5.0.2 on 2024-09-22 21:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_user_nationality_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotrack',
            name='mood',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
